import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const targets = await (await fetch('http://127.0.0.1:9236/json')).json();
const ws = new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.onopen=r);
let id=0; const pending=new Map(); const errors=[];
ws.onmessage=({data})=>{const m=JSON.parse(data); if(m.method==='Runtime.exceptionThrown') errors.push(m.params.exceptionDetails.text); if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}};
const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true})).result.value;
await send('Runtime.enable');
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:'http://127.0.0.1:8127/models'});
await new Promise(r=>setTimeout(r,1600));
assert.equal(await evaluate('document.querySelector("models-page").hidden'),false);
assert.equal(await evaluate('document.querySelector("#settingsDialog").open'),false);
assert.equal(await evaluate('document.querySelector("providers-modal #providerModelsSection")'),null);
assert.equal(await evaluate('getComputedStyle(document.querySelector("harness-chat")).display'),'none');
await evaluate('document.querySelector("#modelsProvidersButton").click()');
assert.equal(await evaluate('document.querySelector("#settingsDialog").open'),true);
await evaluate('document.querySelector("#settingsDialog").close(); document.querySelector("models-page a").click()');
assert.equal(await evaluate('location.pathname'),'/');
assert.equal(await evaluate('document.querySelector("models-page").hidden'),true);
await evaluate('history.back()');
await new Promise(r=>setTimeout(r,300));
assert.equal(await evaluate('location.pathname'),'/models');
assert.equal(await evaluate('document.querySelector("models-page").hidden'),false);
await evaluate('document.querySelector("#providerModelsSearch").value="no-match"; document.querySelector("#providerModelsSearch").dispatchEvent(new Event("input"))');
assert.match(await evaluate('document.querySelector("#providerModelsTableBody").textContent'),/No models match/);
const shot=await send('Page.captureScreenshot',{format:'png'});
await fs.writeFile('screenshots/models-route.png',Buffer.from(shot.data,'base64'));
assert.deepEqual(errors,[]);
console.log('Passed: direct route, providers modal separation, chat navigation, browser back, search, no runtime errors.');
await send('Browser.close');
ws.close();
