import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import { createUiStateStore } from '../lib/ui-state.js';
import { createChangeHistory } from '../lib/change-history.js';

const artifacts = path.resolve('.ui-verification/parity-artifacts');
await fs.mkdir(artifacts, { recursive: true });
const fixture = await fs.mkdtemp(path.join(artifacts, 'run-'));
await fs.mkdir(path.join(fixture, 'db'));
await fs.mkdir(path.join(fixture, 'workspace'));
const workspace = path.join(fixture, 'workspace');
const providerRequests = [];
const modelServer = http.createServer(async (req, res) => {
  if (req.method === 'GET') { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ data: [{ id: 'parity-test' }] })); return; }
  let raw = ''; for await (const chunk of req) raw += chunk;
  const body = JSON.parse(raw); providerRequests.push(body);
  const hasResult = body.messages.some((message) => message.role === 'tool');
  const delta = hasResult ? { content: 'Parity edit completed.' } : { tool_calls: [{ index: 0, id: 'edit1', type: 'function', function: { name: 'edit_files', arguments: JSON.stringify({ edits: [{ path: 'demo.js', old_text: '42', new_text: '43', expected_hash: null }] }) } }] };
  res.writeHead(200, { 'content-type': 'text/event-stream' });
  res.end(`data: ${JSON.stringify({ id: `response-${providerRequests.length}`, choices: [{ delta }], usage: { prompt_tokens: 100, completion_tokens: 20 } })}\n\ndata: [DONE]\n\n`);
});
await new Promise((resolve) => modelServer.listen(0, '127.0.0.1', resolve));
const store = createUiStateStore(path.join(fixture, 'db/ui-state.sqlite'));
const change = await createChangeHistory({ root: workspace, store }).apply([{ path: 'demo.js', content: 'export const answer = 42;\n' }]);
store.set({ providerSettings: { provider: 'custom', model: 'parity-test', baseUrl: `http://127.0.0.1:${modelServer.address().port}/v1`, apiKey: '' } });
const presets = store.getRigConfigurations();
store.setRigConfigurations(presets.configurations.map((preset) => ({ ...preset, componentState: { ...preset.componentState, effects: { ...preset.componentState.effects, composer: false, validation: false } } })), presets.activeConfigurationId);
store.close();
const server = spawn(process.execPath, ['server.js'], { env: { ...process.env, PORT: '8236', AI_HARNESS_DATA_DIR: fixture, AI_HARNESS_WORKSPACE: workspace }, stdio: ['ignore', 'pipe', 'pipe'] });
let output = '';
server.stdout.on('data', (data) => output += data);
server.stderr.on('data', (data) => output += data);
const chrome = spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ['--headless=new', '--disable-gpu', '--no-sandbox', `--user-data-dir=${path.join(fixture, 'chrome')}`, '--remote-debugging-port=9236', 'about:blank'], { stdio: 'ignore' });
let socket;
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function until(fn) { for (let i = 0; i < 100; i++) { try { const result = await fn(); if (result) return result; } catch {} await delay(100); } throw new Error(`Timed out. Server output: ${output}`); }
try {
  await until(async () => (await fetch('http://127.0.0.1:8236/api/health')).ok);
  const pages = await until(async () => (await fetch('http://127.0.0.1:9236/json')).json());
  socket = new WebSocket(pages.find((item) => item.type === 'page').webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
  let id = 0; const pending = new Map(); const errors = [];
  socket.onmessage = ({ data }) => {
    const message = JSON.parse(data);
    if (message.method === 'Runtime.exceptionThrown') errors.push(message.params.exceptionDetails.text + ' ' + (message.params.exceptionDetails.exception?.description || ''));
    if (!message.id) return;
    const task = pending.get(message.id); pending.delete(message.id);
    if (message.error) task.reject(message.error); else task.resolve(message.result);
  };
  const call = (method, params = {}) => new Promise((resolve, reject) => { const request = ++id; pending.set(request, { resolve, reject }); socket.send(JSON.stringify({ id: request, method, params })); });
  const evaluate = async (expression) => {
    const result = await call('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
    if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description || result.exceptionDetails.text);
    return result.result.value;
  };
  await call('Runtime.enable'); await call('Page.enable');
  await call('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1100, deviceScaleFactor: 1, mobile: false });
  await call('Page.navigate', { url: 'http://127.0.0.1:8236' });
  await until(() => evaluate(`!!document.querySelector('tools-modal')`));
  await evaluate(`window.parityRoot = document; for (const dialog of parityRoot.querySelectorAll('dialog[open]')) dialog.close(); parityRoot.querySelector('tools-modal').loadRuntimeSettings().then(() => parityRoot.querySelector('#toolsDialog').showModal())`);
  assert.equal(await evaluate(`parityRoot.querySelector('#runtimeContextMax').value`), '32000');
  await evaluate(`parityRoot.querySelector('#runtimePermissionRules').value = JSON.stringify([{tool:'edit_files',pattern:'*',action:'ask'}]); parityRoot.querySelector('#runtimeContextMax').value = 16000; parityRoot.querySelector('tools-modal').saveRuntimeSettings()`);
  const settings = await (await fetch('http://127.0.0.1:8236/api/runtime-settings')).json();
  assert.equal(settings.settings.context.maxTokens, 16000);
  assert.equal(settings.settings.permissions.rules[0].action, 'ask');
  await evaluate(`parityRoot.querySelector('#loadChangeHistory').click()`);
  await until(() => evaluate(`parityRoot.querySelector('#changeHistoryList').textContent.includes('demo.js')`));
  await evaluate(`parityRoot.querySelector('#changeHistoryList button').click()`);
  await until(() => evaluate(`parityRoot.querySelector('#changeHistoryPreview').textContent.includes('answer = 42')`));
  const screenshot = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
  await fs.writeFile(path.join(artifacts, 'tools-settings.png'), Buffer.from(screenshot.data, 'base64'));
  const undo = await fetch('http://127.0.0.1:8236/api/changes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ workspace, id: change.change_id, action: 'undo' }) });
  assert.equal(undo.status, 200);
  await assert.rejects(fs.stat(path.join(workspace, 'demo.js')), { code: 'ENOENT' });
  const redo = await fetch('http://127.0.0.1:8236/api/changes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ workspace, id: change.change_id, action: 'redo' }) });
  assert.equal(redo.status, 200);
  assert.equal(await fs.readFile(path.join(workspace, 'demo.js'), 'utf8'), 'export const answer = 42;\n');
  await evaluate(`parityRoot.querySelector('#javascriptAction').value = 'symbols'; parityRoot.querySelector('#inspectJavaScript').click()`);
  await until(() => evaluate(`parityRoot.querySelector('#javascriptResults').textContent.includes('answer')`));
  await evaluate(`parityRoot.querySelector('#runtimeContextMax').scrollIntoView()`);
  const lower = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
  await fs.writeFile(path.join(artifacts, 'runtime-settings.png'), Buffer.from(lower.data, 'base64'));
  await evaluate(`parityRoot.querySelector('#toolsDialog').close(); parityRoot.querySelector('#promptInput').value = 'Change the answer to 43'; parityRoot.querySelector('#promptInput').dispatchEvent(new Event('input', { bubbles: true }))`);
  await until(() => evaluate(`!parityRoot.querySelector('#sendButton').disabled`));
  await evaluate(`parityRoot.querySelector('#sendButton').click()`);
  await until(() => evaluate(`!!parityRoot.querySelector('.permissionDialog')`)).catch(async (error) => { console.log(JSON.stringify({ browser: await evaluate('document.body.textContent.slice(-7000)'), requests: providerRequests.length, errors })); throw error; });
  assert.equal(await fs.readFile(path.join(workspace, 'demo.js'), 'utf8'), 'export const answer = 42;\n');
  const permission = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
  await fs.writeFile(path.join(artifacts, 'permission-request.png'), Buffer.from(permission.data, 'base64'));
  await evaluate(`parityRoot.querySelector('.permissionDialog button:last-child').click()`);
  await until(async () => (await fs.readFile(path.join(workspace, 'demo.js'), 'utf8')).includes('43'));
  await until(() => evaluate(`document.body.textContent.includes('Parity edit completed.')`));
  assert.equal(providerRequests.length, 2);
  assert.ok(providerRequests[1].messages.some((message) => message.role === 'tool' && message.content.includes('change_id')));
  const liveOrder = await evaluate(`Array.from(document.querySelector('#messages').children).filter(node => node.matches('.message, .sessionActivity')).map(node => node.matches('.sessionActivity') ? 'run' : node.matches('.message-user') ? 'user' : 'assistant')`);
  assert.deepEqual(liveOrder, ['user', 'run', 'assistant']);
  const saved = await fetch('http://127.0.0.1:8236/api/ui-state', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ state: { sessions: [{ id: 'ordering-regression', title: 'Ordering regression', workspace, messages: [{ role: 'user', text: 'Create a Node.js website' }, { role: 'user', text: 'Style it as a locksmith business' }], events: [{ title: 'Prompt sent', detail: { prompt: 'Create a Node.js website', runId: 'first' }, timestamp: 1 }, { title: 'Error', detail: 'Example failed run', timestamp: 2 }, { title: 'Prompt sent', detail: { prompt: 'Style it as a locksmith business', runId: 'second' }, timestamp: 3 }, { title: 'Response completed', detail: { type: 'response_complete' }, timestamp: 4 }], tokenHistory: [], updatedAt: Date.now() }] } }) });
  assert.equal(saved.status, 200);
  await call('Page.reload');
  await until(() => evaluate(`document.querySelector('#messages')?.textContent.includes('Style it as a locksmith business')`));
  const savedOrder = await evaluate(`Array.from(document.querySelector('#messages').children).filter(node => node.matches('.message, .sessionActivity')).map(node => node.matches('.sessionActivity') ? 'run' : node.matches('.message-user') ? 'user' : 'assistant')`);
  assert.deepEqual(savedOrder, ['user', 'run', 'user', 'run']);
  const orderingScreenshot = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
  await fs.writeFile(path.join(artifacts, 'prompt-run-order.png'), Buffer.from(orderingScreenshot.data, 'base64'));
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'PASS', checks: ['rendered settings', 'saved rules and context budget', 'history list and preview', 'HTTP undo and redo', 'JavaScript symbol UI', 'browser approval before edit', 'structured tool replay', 'live prompt/run/answer order', 'saved prompt-only run order after reload', 'no browser exceptions'], screenshot: path.join(artifacts, 'tools-settings.png') }));
} finally { socket?.close(); server.kill('SIGTERM'); chrome.kill('SIGTERM'); modelServer.closeAllConnections(); modelServer.close(); }
