import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const targets = await (await fetch('http://127.0.0.1:9236/json')).json();
const ws = new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.onopen=r);
let id=0; const pending=new Map(); const errors=[];
ws.onmessage=({data})=>{const m=JSON.parse(data); if(m.method==='Runtime.exceptionThrown') errors.push(m.params.exceptionDetails.text); if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}};
const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true})).result.value;
await send('Runtime.enable');
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});

await send('Page.navigate',{url:'http://localhost:8010/models/77dfeedf-d9db-492e-92f9-5db4a772c5fc'});
await new Promise(r=>setTimeout(r,1800));
assert.equal(await evaluate('document.querySelector("models-page").hidden'), false);
await evaluate('if (!document.querySelector("#appShell").classList.contains("sidebar-collapsed")) document.querySelector("#sidebarToggleButton").click()');
assert.equal(await evaluate('getComputedStyle(document.querySelector("#recentsList")).display'), 'none');
assert.equal(await evaluate('getComputedStyle(document.querySelector("#collapsedModelsLink")).display'), 'flex');
assert.equal(await evaluate('getComputedStyle(document.querySelector("#workspaceMeta")).display'), 'none');
await evaluate('document.querySelector("#collapsedModelsLink").click()');
assert.equal(await evaluate('location.pathname'), '/models');
assert.equal(await evaluate('document.querySelector("#collapsedModelsLink").getAttribute("aria-current")'), 'page');
await evaluate('document.querySelector("#sidebarToggleButton").click()');
assert.notEqual(await evaluate('getComputedStyle(document.querySelector("#recentsList")).display'), 'none');
assert.equal(await evaluate('getComputedStyle(document.querySelector("#collapsedModelsLink")).display'), 'none');
await evaluate('document.querySelector("#providerShortcutButton").click()');
await evaluate('document.querySelector("#addProviderButton").click(); const select = document.querySelector("#providerSelect"); select.value="ollama"; select.dispatchEvent(new Event("change"));');
assert.equal(await evaluate('document.querySelector("#providerApiKeyField").hidden'), false);
assert.match(await evaluate('document.querySelector("#providerApiKeyInput").placeholder'), /Ollama Cloud/);
assert.deepEqual(errors,[]);
console.log('Passed: collapsed history hidden, Models icon navigation, expanded navigation restored, Ollama auth visible, no runtime errors.');
await send('Browser.close');
ws.close();
